### ISSUE TITLE
FE: ToDo List - functionality

### ISSUE THREAD

**Issue by sinakle** [sopra-fs24-group-19/client-group19#20]
Create a functional todo list

**Comment by nina22221111** [comment]
for now i can only post a todo, not yet see it: e08deaf

both can see todos but there is not yet distinction between who did what in order to make available the edit and delete button: 09c273d

fixed styling a bit: 12a5a40

there is a distinction between mytodos and other todos: 627557d

you can edit a description, but there is still a minor ishue when you are typing in that it reverts back: 469e856

i can see creator and helpers id: 42d501b

checking out a todo by creator works: 59401cd
